#!/usr/bin/env python
import MySQLdb

db=MySQLdb.connect("localhost","auto","myvice12","main")
curs=db.cursor()
print("Database main selected")
print("Printing table office_temp")
curs.execute("select * from office_temp")

for reading in curs.fetchall():
	print(str(reading[0])+"  "+str(reading[1])+"  "+str(reading[2])+"  "+str(reading[3]))

print("Closing Database and exiting")
db.close()
